'use client';
import { ArrowUpRight, ArrowRight, Lightbulb, Database, LayoutGrid, Link2, TriangleAlert, Sparkles, Settings, Box, ChartNoAxesColumn, Pause, Play } from 'lucide-react';
const inputs = [[Lightbulb,'Idea'],[Database,'Data'],[LayoutGrid,'Workflow'],[Link2,'Existing system'],[TriangleAlert,'Hard problem']] as const;
const outputs = [[Sparkles,'AI product','From prototype to production'],[Settings,'Automation','Less manual work. More momentum.'],[Box,'Platform','Built around your business'],[ChartNoAxesColumn,'Working system','Ready for the real world']] as const;
export default function EngineeringHero({contact,paused,onPause,onMenu}:{contact:string;paused:boolean;onPause:()=>void;onMenu:()=>void}) {
 return <section className={`engineering-shell ${paused?'engineering-paused':''}`} aria-label="Forward deployed engineering">
  <header className="engineering-nav"><a href="#top" className="engineering-logo">eigi_ai<span>/ FDE</span></a><nav aria-label="Main navigation"><a href="#approach">What we do</a><a href="#method">Process</a><a href="#capabilities">Possibilities</a><a href="#experience">Experience</a></nav><div className="engineering-actions"><button onClick={onPause} aria-label={paused?'Play animations':'Pause animations'} aria-pressed={paused}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><a href={contact}>Talk to us <ArrowUpRight size={15}/></a><button className="engineering-menu" onClick={onMenu}>Menu</button></div></header>
  <div className="engineering-body">
   <div className="engineering-intro"><div><p className="engineering-kicker">FORWARD DEPLOYED ENGINEERING</p><h1>Your hardest problems.<br/><span>Our engineers, deployed.</span></h1><p className="engineering-description">We embed with your team to design, build, and deploy<br className="engineering-break"/> AI products, software, and systems that work.</p><div className="engineering-ctas"><a className="engineering-primary" href={contact}>Deploy an engineer <ArrowRight size={18}/></a><a href="#capabilities">Explore the possibilities <ArrowUpRight size={17}/></a></div><p className="engineering-process">Understand <span>·</span> Design <span>·</span> Build <span>·</span> Integrate <span>·</span> Deploy</p></div><p className="engineering-promise">Built for the future.<br/><span>Available today.</span></p></div>
   <div className="engineering-system" aria-label="Your challenges, connected by Eigi_ai engineers to useful outcomes">
    <div className="engineering-inputs"><p className="engineering-kicker">YOUR CHALLENGES</p>{inputs.map(([Icon,label])=><div className="engineering-node" key={label}><Icon size={19}/><span>{label}</span></div>)}</div>
    <svg className="engineering-wires" viewBox="0 0 1200 330" preserveAspectRatio="none" aria-hidden="true"><defs><linearGradient id="wire-light"><stop stopColor="#898781"/><stop offset=".5" stopColor="#f8e6c6"/><stop offset="1" stopColor="#b7aca0"/></linearGradient></defs>{[58,110,162,214,266].map((y,i)=><g key={y}><path d={`M 224 ${y} H 280 C 345 ${y}, 350 ${125+i*18}, 430 ${125+i*18} H 500`} /><path className="engineering-signal" style={{animationDelay:`${i*-.7}s`}} d={`M 224 ${y} H 280 C 345 ${y}, 350 ${125+i*18}, 430 ${125+i*18} H 500`} /></g>)}{[70,135,200,265].map((y,i)=><g key={y}><path d={`M 700 ${130+i*22} H 760 C 825 ${130+i*22}, 820 ${y}, 880 ${y} H 960`}/><path className="engineering-signal" style={{animationDelay:`${i*-.9}s`}} d={`M 700 ${130+i*22} H 760 C 825 ${130+i*22}, 820 ${y}, 880 ${y} H 960`}/></g>)}</svg>
    <div className="engineering-core-area"><p className="engineering-core-tag"><i/> ENGINEERS, EMBEDDED</p><div className="engineering-core" aria-hidden="true">{[0,1,2,3,4].map(i=><div className="engineering-glass" key={i} style={{transform:`translateZ(${i*20-40}px)`}}/>)}<div className="engineering-core-brand"><span>e</span><strong>eigi_ai</strong></div></div><p className="engineering-core-caption">TURNING COMPLEXITY<br/>INTO PROGRESS</p></div>
    <div className="engineering-outputs"><p className="engineering-kicker">YOUR OUTCOMES</p>{outputs.map(([Icon,label,copy])=><div className="engineering-node" key={label}><Icon size={22}/><div><strong>{label}</strong><small>{copy}</small></div><i/></div>)}</div>
   </div>
   <div className="engineering-baseline"><span>ENGINEERS ON YOUR TEAM. FROM DAY ONE.</span><a href="#approach">A more capable tomorrow <ArrowRight size={15}/></a></div>
  </div>
 </section>;
}
